import type { DesignCardData } from "@/components/design-card"

export const designCards: DesignCardData[] = [
  {
    id: "1",
    image: "/cards/card-network.png",
    alt: "Node-based API diagram interface",
    aspect: "aspect-[4/3]",
    avatarColor: "bg-gold-highlight",
    tag: "Interface",
    title: "Serverless Flow Builder",
    author: "Mina Cho",
    description:
      "A node-based canvas for wiring up serverless workers and APIs, with live connection previews and inline compute cost estimates.",
    timeAgo: "4h ago",
    impressions: "8.2K",
    outbound: 21,
    source: "X",
    category: "Interface",
    style: "Minimal",
    color: "Light",
    interaction: ["Drag & drop", "Live preview"],
  },
  {
    id: "2",
    image: "/cards/card-dark-hero.png",
    alt: "Dark mode website hero with glowing panels",
    aspect: "aspect-[16/10]",
    avatarColor: "bg-gold-bright",
    tag: "Web",
    title: "Render Cost, Halved",
    author: "Theo Park",
    description:
      "A dark hero section built around three glowing gradient panels, pairing a bold claim with soft ambient light to sell a performance story.",
    timeAgo: "6h ago",
    impressions: "14.6K",
    outbound: 38,
    source: "X",
    category: "Web",
    style: "Bold",
    color: "Dark",
    interaction: ["Scroll reveal"],
  },
  {
    id: "3",
    image: "/cards/card-spheres.png",
    alt: "Four glossy spheres of different materials",
    aspect: "aspect-square",
    avatarColor: "bg-gold-core",
    tag: "3D",
    title: "Material Study, No. 4",
    author: "Aya Nakamura",
    description:
      "Four spheres rendered in marble, glass, obsidian and frosted acrylic, arranged as a quiet study in light and material response.",
    timeAgo: "9h ago",
    impressions: "6.1K",
    outbound: 9,
    source: "Instagram",
    category: "3D",
    style: "Minimal",
    color: "Light",
    interaction: ["Static"],
  },
  {
    id: "4",
    image: "/cards/card-dashboard-black.png",
    alt: "Dark futuristic dashboard interface",
    aspect: "aspect-[4/3]",
    badge: "star",
    avatarColor: "bg-gold-deep",
    tag: "Product",
    title: "Signal Dashboard",
    author: "Eujin",
    description:
      "A black-on-black operations dashboard with thin gauge lines and monospace readouts, built for scanning system health at a glance.",
    timeAgo: "2d ago",
    impressions: "10.8K",
    outbound: 12,
    source: "X",
    category: "Product",
    style: "Minimal",
    color: "Dark",
    interaction: ["Transitions", "Microinteraction"],
  },
  {
    id: "5",
    image: "/cards/card-zebra-field.png",
    alt: "Toy zebra on a miniature wildflower field",
    aspect: "aspect-[16/11]",
    avatarColor: "bg-gray-medium",
    tag: "Illustration",
    title: "Field Study",
    author: "Noor Malik",
    description:
      "A whimsical isometric scene of a toy zebra resting in a miniature wildflower field, rendered with soft pastel studio lighting.",
    timeAgo: "1d ago",
    impressions: "5.4K",
    outbound: 15,
    source: "Instagram",
    category: "Illustration",
    style: "Playful",
    color: "Light",
    interaction: ["Static"],
  },
  {
    id: "6",
    image: "/cards/card-notepad.png",
    alt: "Minimal notepad UI card",
    aspect: "aspect-[4/5]",
    avatarColor: "bg-gold-highlight",
    tag: "Interface",
    title: "Quiet Notes",
    author: "Sam Ortiz",
    description:
      "A distraction-free notes surface floating on black, with thin placeholder rules and quiet corner controls that stay out of the way.",
    timeAgo: "3d ago",
    impressions: "7.9K",
    outbound: 6,
    source: "X",
    category: "Interface",
    style: "Minimal",
    color: "Dark",
    interaction: ["Focus mode"],
  },
  {
    id: "7",
    image: "/cards/card-scatter.png",
    alt: "Scattered 3D objects with annotation lines",
    aspect: "aspect-[4/5]",
    avatarColor: "bg-gold-bright",
    tag: "3D",
    title: "Annotated Objects",
    author: "Priya Desai",
    description:
      "Small rendered objects scattered across white space, connected by thin annotation lines that map out a tiny design system.",
    timeAgo: "5h ago",
    impressions: "4.3K",
    outbound: 4,
    source: "Website",
    category: "3D",
    style: "Minimal",
    color: "Light",
    interaction: ["Static"],
  },
  {
    id: "8",
    image: "/cards/card-abstract-canvas.png",
    alt: "Abstract editorial paper illustration",
    aspect: "aspect-[3/4]",
    avatarColor: "bg-gold-core",
    tag: "Editorial",
    title: "Torn Paper Study",
    author: "Lucas Bergman",
    description:
      "A quiet editorial composition on textured paper, pairing a single torn shape with a thin ink line and generous negative space.",
    timeAgo: "11h ago",
    impressions: "3.7K",
    outbound: 7,
    source: "Website",
    category: "Editorial",
    style: "Minimal",
    color: "Light",
    interaction: ["Static"],
  },
  {
    id: "9",
    image: "/cards/card-sneaker.png",
    alt: "Floating sneaker product render",
    aspect: "aspect-[4/3]",
    avatarColor: "bg-gold-deep",
    badge: 4,
    tag: "Product",
    title: "Ecommerce Hero Shot",
    author: "Jade Whitfield",
    description:
      "A single sneaker rendered at a floating angle on studio gray, the kind of product shot built to be dropped straight into a hero.",
    timeAgo: "22h ago",
    impressions: "9.5K",
    outbound: 17,
    source: "X",
    category: "Product",
    style: "Minimal",
    color: "Light",
    interaction: ["Static"],
  },
  {
    id: "10",
    image: "/cards/card-typeset.png",
    alt: "Editorial typography poster crop",
    aspect: "aspect-[3/4]",
    avatarColor: "bg-gray-medium",
    tag: "Typography",
    title: "Cropped Serif Study",
    author: "Rune Andersen",
    description:
      "A tightly cropped serif letterform poster on cream paper, leaning entirely on scale, grain and contrast to carry the composition.",
    timeAgo: "16h ago",
    impressions: "5.9K",
    outbound: 10,
    source: "Instagram",
    category: "Typography",
    style: "Editorial",
    color: "Light",
    interaction: ["Static"],
  },
]
